title = "Jason Koh"
languageCode = "en-us"
baseurl = "http://jbkoh.github.io/"
author = "Jason Koh"
theme = "hugo-academic"
disqusShortname = "bk7749"
[Params]
  email = "jbkoh@eng.ucsd.edu"
  github = "jbkoh"
  date_format = "aaaaaaaaaa"

[[menu.main]]
  name = "Main"
  url = "#about"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "#publications_selected"
  weight = 2

[[menu.main]]
  name = "Posts"
  url = "#posts"
  weight = 3

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 4

[[menu.main]]
  name = "Teaching"
  url = "#teaching"
  weight = 5

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 6


