title = "Jason Koh"
languageCode = "en-us"
copyright = "&copy; 2019 Jason Koh"
baseurl = "http://jbkoh.github.io/"
author = "Jason Koh"
theme = "hugo-academic"
enableEmoji = true
disqusShortname = "bk7749"

[blackfriday]
  hrefTargetBlank = true

[params]
    name = "Jason Koh"
    organization = "University of California, San Diego"
    email = "jbkoh@eng.ucsd.edu"
    github = "jbkoh"
    date_format = "2016-01-02"
    avatar = "jbkoh.jpg"
    sharing = true

    [[params.social]]
        icon = "envelope"
        icon_pack = "fa"
        link = "mailto:jbkoh@eng.ucsd.edu"
    [[params.social]]
        icon = "google-scholar"
        icon_pack = "ai"
        link = "https://scholar.google.com/citations?user=G1KvxoUAAAAJ&hl=en"
    [[params.social]]
        icon = "github"
        icon_pack = "fa"
        link = "https://github.com/jbkoh"

    [[menu.main]]
        name = "Main"
        url = "#about"
        weight = 1

    [[menu.main]]
        name = "Publications"
        url = "#publications"
        #url = "#publications_selected"
        weight = 2
    
    [[menu.main]]
        name = "Source Code"
        url = "#source_code"
        weight = 3

    [[menu.main]]
        name = "Posts"
        url = "#posts"
        weight = 4

    [[menu.main]]
        name = "Projects"
        url = "#projects"
        weight = 5
    
    [[menu.main]]
        name = "Contact"
        url = "#contact"
        weight = 6


